class CakeTester{
	public static void main(String eat[]){
		Cake cake=new Cake("Round","Truffle","Two Tier",2,"White",2048);
		System.out.println("Design:"+cake.design+"  |Shape:"+cake.shape+"  |Flavour:"+cake.flavour+"  |Color:"+cake.color+"  |Weight:"+cake.weight+"  |Price in Rs:"+cake.price);
		Cake cake1=new Cake("Round","Chocolate","One Tier Panda",2,"White",1148);
		System.out.println("Design:"+cake1.design+"  |Shape:"+cake1.shape+"  |Flavour:"+cake1.flavour+"  |Color:"+cake1.color+"  |Weight:"+cake1.weight+"  |Price in Rs:"+cake1.price);
		Cake cake2=new Cake("Hear"," Chocolate Truffle","Two Tier",0.5,"Brown",548);
		System.out.println("Design:"+cake2.design+"  |Shape:"+cake2.shape+"  |Flavour:"+cake2.flavour+"  |Color:"+cake2.color+"  |Weight:"+cake2.weight+"  |Price in Rs:"+cake2.price);
		Cake cake3=new Cake("Round","Chocolate","One Tier",0.5,"Brown",749);
		System.out.println("Design:"+cake3.design+"  |Shape:"+cake3.shape+"  |Flavour:"+cake3.flavour+"  |Color:"+cake3.color+"  |Weight:"+cake3.weight+"  |Price in Rs:"+cake3.price);
		Cake cake4=new Cake("Round","Butter Scotch","Two Tier",3,"White",2648);
		System.out.println("Design:"+cake4.design+"  |Shape:"+cake4.shape+"  |Flavour:"+cake4.flavour+"  |Color:"+cake4.color+"  |Weight:"+cake4.weight+"  |Price in Rs:"+cake4.price);
		Cake cake5=new Cake("Round","Butter Scotch","One Tier",3,"White",1648);		
		System.out.println("Design:"+cake5.design+"  |Shape:"+cake5.shape+"  |Flavour:"+cake5.flavour+"  |Color:"+cake5.color+"  |Weight:"+cake5.weight+"  |Price in Rs:"+cake5.price);
		Cake cake6=new Cake("Round","Chocolate","One Tier Panda",3,"White",1167);
		System.out.println("Design:"+cake5.design+"  |Shape:"+cake5.shape+"  |Flavour:"+cake5.flavour+"  |Color:"+cake5.color+"  |Weight:"+cake5.weight+"  |Price in Rs:"+cake5.price);
		Cake cake7=new Cake("Heart","Chocolat Truffle ","Two  Tier Panda",3,"White",2167);
		System.out.println("Design:"+cake7.design+"  |Shape:"+cake7.shape+"  |Flavour:"+cake7.flavour+"  |Color:"+cake7.color+"  |Weight:"+cake7.weight+"  |Price in Rs:"+cake7.price);
		Cake cake8=new Cake("Round","Chocolate  ","One  Tier ",0.5,"Brown",749);
		System.out.println("Design:"+cake8.design+"  |Shape:"+cake8.shape+"  |Flavour:"+cake8.flavour+"  |Color:"+cake8.color+"  |Weight:"+cake8.weight+"  |Price in Rs:"+cake8.price);
		Cake cake9=new Cake("Round"," Butter Scotch"," Two Tier ",1.5,"Brown",2749);
		System.out.println("Design:"+cake9.design+"  |Shape:"+cake9.shape+"  |Flavour:"+cake9.flavour+"  |Color:"+cake9.color+"  |Weight:"+cake9.weight+"  |Price in Rs:"+cake9.price);
		Cake cake10=new Cake("Round"," Butter Scotch"," Two Tier ",1.5,"Cream",2049);
		System.out.println("Design:"+cake10.design+"  |Shape:"+cake10.shape+"  |Flavour:"+cake10.flavour+"  |Color:"+cake10.color+"  |Weight:"+cake10.weight+"  |Price in Rs:"+cake10.price);
		Cake cake11=new Cake("Round"," Truffle"," Two Tier ",2,"Cream",2999);
		System.out.println("Design:"+cake11.design+"  |Shape:"+cake11.shape+"  |Flavour:"+cake11.flavour+"  |Color:"+cake11.color+"  |Weight:"+cake11.weight+"  |Price in Rs:"+cake11.price);
		Cake cake12=new Cake("Round"," Truffle"," One Tier ",2,"Cream",2099);
		System.out.println("Design:"+cake12.design+"  |Shape:"+cake12.shape+"  |Flavour:"+cake12.flavour+"  |Color:"+cake12.color+"  |Weight:"+cake12.weight+"  |Price in Rs:"+cake12.price);
		Cake cake13=new Cake("Round"," Truffle","Two Tier ",2,"Cream",2049);
		System.out.println("Design:"+cake13.design+"  |Shape:"+cake13.shape+"  |Flavour:"+cake13.flavour+"  |Color:"+cake13.color+"  |Weight:"+cake13.weight+"  |Price in Rs:"+cake13.price);
		Cake cake14=new Cake("Square","Pine Apple ","Two Tier ",1,"White",1543);
		System.out.println("Design:"+cake14.design+"  |Shape:"+cake14.shape+"  |Flavour:"+cake14.flavour+"  |Color:"+cake14.color+"  |Weight:"+cake14.weight+"  |Price in Rs:"+cake14.price);
		Cake cake15=new Cake("Heart"," Chocolate","One Tier ",2,"Cream",3453);
		System.out.println("Design:"+cake15.design+"  |Shape:"+cake15.shape+"  |Flavour:"+cake15.flavour+"  |Color:"+cake15.color+"  |Weight:"+cake15.weight+"  |Price in Rs:"+cake15.price);
		Cake cake16=new Cake("Round"," Black Forest","One Tier ",2,"Cream",3253);
		System.out.println("Design:"+cake16.design+"  |Shape:"+cake16.shape+"  |Flavour:"+cake16.flavour+"  |Color:"+cake16.color+"  |Weight:"+cake16.weight+"  |Price in Rs:"+cake16.price);
		Cake cake17=new Cake("Round"," Strawberry","One Tier ",1,"White",1553);
		System.out.println("Design:"+cake17.design+"  |Shape:"+cake17.shape+"  |Flavour:"+cake17.flavour+"  |Color:"+cake17.color+"  |Weight:"+cake17.weight+"  |Price in Rs:"+cake17.price);
		Cake cake18=new Cake("Round"," Strawberry","One Tier ",2,"Pink",1553);
		System.out.println("Design:"+cake18.design+"  |Shape:"+cake18.shape+"  |Flavour:"+cake18.flavour+"  |Color:"+cake18.color+"  |Weight:"+cake18.weight+"  |Price in Rs:"+cake18.price);
		Cake cake19=new Cake("Round"," Strawberry","Two Tier ",1,"White",553);
		System.out.println("Design:"+cake19.design+"  |Shape:"+cake19.shape+"  |Flavour:"+cake19.flavour+"  |Color:"+cake19.color+"  |Weight:"+cake19.weight+"  |Price in Rs:"+cake19.price);
		Cake cake20=new Cake("Round","Venilla ","One Tier ",1,"White",4248);
		System.out.println("Design:"+cake20.design+"  |Shape:"+cake20.shape+"  |Flavour:"+cake20.flavour+"  |Color:"+cake20.color+"  |Weight:"+cake20.weight+"  |Price in Rs:"+cake20.price);
		Cake cake21=new Cake("Round","Venilla ","Two Tier ",1,"White",3248);
		System.out.println("Design:"+cake21.design+"  |Shape:"+cake21.shape+"  |Flavour:"+cake21.flavour+"  |Color:"+cake21.color+"  |Weight:"+cake21.weight+"  |Price in Rs:"+cake21.price);
		Cake cake22=new Cake("Heart","Venilla ","Two Tier ",2,"White",2148);	
		System.out.println("Design:"+cake22.design+"  |Shape:"+cake22.shape+"  |Flavour:"+cake22.flavour+"  |Color:"+cake22.color+"  |Weight:"+cake22.weight+"  |Price in Rs:"+cake22.price);
		Cake cake23=new Cake("Hear"," Chocolate Truffle","Two Tier",0.5,"Brown",1548);
		System.out.println("Design:"+cake23.design+"  |Shape:"+cake23.shape+"  |Flavour:"+cake23.flavour+"  |Color:"+cake23.color+"  |Weight:"+cake23.weight+"  |Price in Rs:"+cake23.price);
		Cake cake24=new Cake("Hear"," Chocolate Truffle","One Tier",0.5,"Brown",548);
		System.out.println("Design:"+cake24.design+"  |Shape:"+cake24.shape+"  |Flavour:"+cake24.flavour+"  |Color:"+cake24.color+"  |Weight:"+cake24.weight+"  |Price in Rs:"+cake24.price);
	}	
}