class CakeTester{
	public static void main(String eat[]){
		Cake cake=new Cake();
		cake.shape="Round";
		cake.flavour="Truffle";
		cake.design="Two Tier";
		cake.color="White";
		cake.weight=2;
		cake.price=2048;
		cake.eatCake();
		System.out.println("Design:"+cake.design+"  |Shape:"+cake.shape+"  |Flavour:"+cake.flavour+"  |Color:"+cake.color+"  |Weight:"+cake.weight+"  |Price in Rs:"+cake.price);
		Cake cake1=new Cake();
		cake1.shape="Round";
		cake1.flavour="Chocolate";
		cake1.design="One Tier Panda";
		cake1.color="White";
		cake1.weight=1;
		cake1.price=1148;
		cake.eatCake();
		System.out.println("Design:"+cake1.design+"  |Shape:"+cake1.shape+"  |Flavour:"+cake1.flavour+"  |Color:"+cake1.color+"  |Weight:"+cake1.weight+"  |Price in Rs:"+cake1.price);
		Cake cake2=new Cake();
		cake2.shape="Hear";
		cake2.flavour=" Chocolate Truffle";
		cake2.design="Two Tier";
		cake2.color="Brown";
		cake2.weight=0.5;
		cake2.price=548;
		cake.eatCake();
		System.out.println("Design:"+cake2.design+"  |Shape:"+cake2.shape+"  |Flavour:"+cake2.flavour+"  |Color:"+cake2.color+"  |Weight:"+cake2.weight+"  |Price in Rs:"+cake2.price);
		Cake cake3=new Cake();
		cake3.shape="Round";
		cake3.flavour="Chocolate";
		cake3.design="One Tier";
		cake3.color="Brown";
		cake3.weight=0.5;
		cake3.price=749;
		cake.eatCake();
		System.out.println("Design:"+cake3.design+"  |Shape:"+cake3.shape+"  |Flavour:"+cake3.flavour+"  |Color:"+cake3.color+"  |Weight:"+cake3.weight+"  |Price in Rs:"+cake3.price);
		Cake cake4=new Cake();
		cake4.shape="Round";
		cake4.flavour="Butter Scotch";
		cake4.design="Two Tier";
		cake4.color="White";
		cake.weight=1.5;
		cake4.price=2648;
		cake.eatCake();
		System.out.println("Design:"+cake4.design+"  |Shape:"+cake4.shape+"  |Flavour:"+cake4.flavour+"  |Color:"+cake4.color+"  |Weight:"+cake4.weight+"  |Price in Rs:"+cake4.price);
		Cake cake5=new Cake();
		cake5.shape="Round";
		cake5.flavour="Butter Scotch";
		cake5.design="One Tier";
		cake5.color="Cream";
		cake5.weight=2;
		cake5.price=2048;
		cake.eatCake();
		System.out.println("Design:"+cake5.design+"  |Shape:"+cake5.shape+"  |Flavour:"+cake5.flavour+"  |Color:"+cake5.color+"  |Weight:"+cake5.weight+"  |Price in Rs:"+cake5.price);
		Cake cake6=new Cake();
		cake6.shape="Round";
		cake6.flavour="Truffle";
		cake6.design="Two Tier";
		cake6.color="White";
		cake.weight=2;
		cake6.price=2999;
		cake.eatCake();
		System.out.println("Design:"+cake6.design+"  |Shape:"+cake6.shape+"  |Flavour:"+cake6.flavour+"  |Color:"+cake6.color+"  |Weight:"+cake6.weight+"  |Price in Rs:"+cake6.price);
		Cake cake7=new Cake();
		cake7.shape="Round";
		cake7.flavour="Truffle";
		cake7.design="One Tier";
		cake7.color="White";
		cake7.weight=2;
		cake7.price=2048;
		cake.eatCake();
		System.out.println("Design:"+cake7.design+"  |Shape:"+cake7.shape+"  |Flavour:"+cake7.flavour+"  |Color:"+cake7.color+"  |Weight:"+cake7.weight+"  |Price in Rs:"+cake7.price);
		Cake cake8=new Cake();
		cake8.shape="Heart";
		cake8.flavour="Truffle";
		cake8.design="Two Tier";
		cake8.color="White";
		cake8.weight=2;
		cake8.price=2048;
		cake8.eatCake();
		System.out.println("Design:"+cake8.design+"  |Shape:"+cake8.shape+"  |Flavour:"+cake8.flavour+"  |Color:"+cake8.color+"  |Weight:"+cake8.weight+"  |Price in Rs:"+cake8.price);
		Cake cake9=new Cake();
		cake9.shape="Square";
		cake9.flavour="Pine Apple";
		cake9.design="Two Tier";
		cake9.color="White";
		cake9.weight=1;
		cake9.price=1548;
		cake9.eatCake();
		System.out.println("Design:"+cake9.design+"  |Shape:"+cake9.shape+"  |Flavour:"+cake9.flavour+"  |Color:"+cake9.color+"  |Weight:"+cake9.weight+"  |Price in Rs:"+cake9.price);
		Cake cake10=new Cake();
		cake10.shape="Heart";
		cake10.flavour="Chocolate";
		cake10.design="One Tier";
		cake10.color="Cream";
		cake10.weight=2;
		cake10.price=3999;
		cake.eatCake();
		System.out.println("Design:"+cake10.design+"  |Shape:"+cake10.shape+"  |Flavour:"+cake10.flavour+"  |Color:"+cake10.color+"  |Weight:"+cake10.weight+"  |Price in Rs:"+cake10.price);
		Cake cake11=new Cake();
		cake11.shape="Round";
		cake11.flavour="Black Forest";
		cake11.design="Two Tier";
		cake11.color="White";
		cake11.weight=2;
		cake11.price=2048;
		cake.eatCake();
		System.out.println("Design:"+cake11.design+"  |Shape:"+cake11.shape+"  |Flavour:"+cake11.flavour+"  |Color:"+cake11.color+"  |Weight:"+cake11.weight+"  |Price in Rs:"+cake11.price);
		Cake cake12=new Cake();
		cake12.shape="Round";
		cake12.flavour="Truffle";
		cake12.design="One Tier";
		cake12.color="Pink";
		cake12.weight=1;
		cake12.price=1048;
		cake.eatCake();
		System.out.println("Design:"+cake12.design+"  |Shape:"+cake12.shape+"  |Flavour:"+cake12.flavour+"  |Color:"+cake12.color+"  |Weight:"+cake12.weight+"  |Price in Rs:"+cake12.price);
		Cake cake13=new Cake();
		cake13.shape="Round";
		cake13.flavour="Strawberry";
		cake13.design="Two Tier";
		cake13.color="White";
		cake13.weight=1;
		cake13.price=1548;
		cake.eatCake();
		System.out.println("Design:"+cake13.design+"  |Shape:"+cake13.shape+"  |Flavour:"+cake13.flavour+"  |Color:"+cake13.color+"  |Weight:"+cake13.weight+"  |Price in Rs:"+cake13.price);
		Cake cake14=new Cake();
		cake14.shape="Diamond";
		cake14.flavour="Truffle";
		cake14.design="Two Tier";
		cake14.color="White";
		cake14.weight=2;
		cake14.price=3448;
		cake.eatCake();
		System.out.println("Design:"+cake14.design+"  |Shape:"+cake14.shape+"  |Flavour:"+cake14.flavour+"  |Color:"+cake14.color+"  |Weight:"+cake14.weight+"  |Price in Rs:"+cake14.price);
		Cake cake15=new Cake();
		cake15.shape="Round";
		cake15.flavour="Venilla";
		cake15.design="Two Tier";
		cake15.color="White";
		cake15.weight=2;
		cake15.price=4248;
		cake.eatCake();
		System.out.println("Design:"+cake15.design+"  |Shape:"+cake15.shape+"  |Flavour:"+cake15.flavour+"  |Color:"+cake15.color+"  |Weight:"+cake15.weight+"  |Price in Rs:"+cake15.price);
		Cake cake16=new Cake();
		cake16.shape="Square";
		cake16.flavour="Truffle";
		cake16.design="One Tier";
		cake16.color="Creame";
		cake16.weight=2;
		cake16.price=999;
		cake.eatCake();
		System.out.println("Design:"+cake16.design+"  |Shape:"+cake16.shape+"  |Flavour:"+cake16.flavour+"  |Color:"+cake16.color+"  |Weight:"+cake16.weight+"  |Price in Rs:"+cake16.price);
		Cake cake17=new Cake();
		cake17.shape="Round";
		cake17.flavour="Venilla";
		cake17.design="Two Tier";
		cake17.color="Pink";
		cake17.weight=2;
		cake17.price=3248;
		cake.eatCake();
		System.out.println("Design:"+cake17.design+"  |Shape:"+cake17.shape+"  |Flavour:"+cake17.flavour+"  |Color:"+cake17.color+"  |Weight:"+cake17.weight+"  |Price in Rs:"+cake17.price);
		Cake cake18=new Cake();
		cake18.shape="Round";
		cake18.flavour="Black Forest";
		cake18.design="Two Tier";
		cake18.color="White";
		cake18.weight=2;
		cake18.price=1768;
		cake.eatCake();
		System.out.println("Design:"+cake18.design+"  |Shape:"+cake18.shape+"  |Flavour:"+cake18.flavour+"  |Color:"+cake18.color+"  |Weight:"+cake18.weight+"  |Price in Rs:"+cake18.price);
		Cake cake19=new Cake();
		cake19.shape="Round";
		cake19.flavour="ButterScotch";
		cake19.design="Three Tier";
		cake19.color="White";
		cake19.weight=2;
		cake19.price=4532;
		cake.eatCake();
		System.out.println("Design:"+cake19.design+"  |Shape:"+cake19.shape+"  |Flavour:"+cake19.flavour+"  |Color:"+cake19.color+"  |Weight:"+cake19.weight+"  |Price in Rs:"+cake19.price);
		Cake cake20=new Cake();
		cake20.shape="Round";
		cake20.flavour="Truffle";
		cake20.design="Two Tier";
		cake20.color="White";
		cake20.weight=1;
		cake20.price=987;
		cake.eatCake();
		System.out.println("Design:"+cake20.design+"  |Shape:"+cake20.shape+"  |Flavour:"+cake20.flavour+"  |Color:"+cake20.color+"  |Weight:"+cake20.weight+"  |Price in Rs:"+cake20.price);
	}
}