class SpecsTester{
	public static void main(String lens[]){
	Specs spec1=new Specs();
	spec1.frameColor="Black";
	spec1.brandName="lensKart";
	spec1.price=1768;
	spec1.lens="-0.50";
	spec1.frameWidth=133;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec1.brandName+" |Frame Color: "+spec1.frameColor+" |Price: "+spec1.price+" |Type of Lens: "+spec1.lens+" |Frame Width: "+	spec1.frameWidth);
	Specs spec2=new Specs();
	spec2.frameColor="White";
	spec2.brandName="lensKart";
	spec2.price=1758 ;
	spec2.lens="-0.60";
	spec2.frameWidth=123;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec2.brandName+" |Frame Color: "+spec2.frameColor+" |Price: "+spec2.price+" |Type of Lens: "+spec2.lens+" |Frame Width: "+	spec2.frameWidth);
	Specs spec3=new Specs();
	spec3.frameColor="Brown";
	spec3.brandName="lensKart";
	spec3.price=1268 ;
	spec3.lens="-0.30";
	spec3.frameWidth=113;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec3.brandName+" |Frame Color: "+spec3.frameColor+" |Price: "+spec3.price+" |Type of Lens: "+spec3.lens+" |Frame Width: "+	spec3.frameWidth);
	Specs spec4=new Specs();
	spec4.frameColor="Beige";
	spec4.brandName="lensKart";
	spec4.price=2768 ;
	spec4.lens="-0.50";
	spec4.frameWidth=136;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec4.brandName+" |Frame Color: "+spec4.frameColor+" |Price: "+spec4.price+" |Type of Lens: "+spec4.lens+" |Frame Width: "+	spec4.frameWidth);
	Specs spec5=new Specs();
	spec5.frameColor="White";
	spec5.brandName="lensKart";
	spec5.price=768 ;
	spec5.lens="-0.50";
	spec5.frameWidth=133;
	System.out.println("Brand Name: "+spec5.brandName+" |Frame Color: "+spec5.frameColor+" |Price: "+spec5.price+" |Type of Lens: "+spec5.lens+" |Frame Width: "+	spec5.frameWidth);
	Specs spec6=new Specs();
	spec6.frameColor="Black";
	spec6.brandName="lensKart";
	spec6.price=3768 ;
	spec6.lens="-0.50";
	spec6.frameWidth=133;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec6.brandName+" |Frame Color: "+spec6.frameColor+" |Price: "+spec6.price+" |Type of Lens: "+spec6.lens+" |Frame Width: "+	spec6.frameWidth);
	Specs spec7=new Specs();
	spec7.frameColor="Yellow";
	spec7.brandName="lensKart";
	spec7.price=2788 ;
	spec7.lens="-0.30";
	spec7.frameWidth=113;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec7.brandName+" |Frame Color: "+spec7.frameColor+" |Price: "+spec7.price+" |Type of Lens: "+spec7.lens+" |Frame Width: "+	spec7.frameWidth);
	Specs spec8=new Specs();
	spec8.frameColor="Pink";
	spec8.brandName="lensKart";
	spec8.price=1660 ;
	spec8.lens="-0.5";
	spec8.frameWidth=133;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec8.brandName+" |Frame Color: "+spec8.frameColor+" |Price: "+spec8.price+" |Type of Lens: "+spec8.lens+" |Frame Width: "+	spec8.frameWidth);
	Specs spec9=new Specs();
	spec9.frameColor="Purple";
	spec9.brandName="lensKart";
	spec9.price=1468 ;
	spec9.lens="-0.50";
	spec9.frameWidth=132;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec9.brandName+" |Frame Color: "+spec9.frameColor+" |Price: "+spec9.price+" |Type of Lens: "+spec9.lens+" |Frame Width: "+	spec9.frameWidth);
	Specs spec10=new Specs();
	spec10.frameColor="Blue";
	spec10.brandName="lensKart";
	spec10.price=1729 ;
	spec10.lens="-0.50";
	spec10.frameWidth=133;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec10.brandName+" |Frame Color: "+spec10.frameColor+" |Price: "+spec10.price+" |Type of Lens: "+spec10.lens+" |Frame Width: "+	spec10.frameWidth);
	Specs spec11=new Specs();
	spec11.frameColor="Prussian Blue";
	spec11.brandName="lensKart";
	spec11.price=1568 ;
	spec11.lens="-0.30";
	spec11.frameWidth=133;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec11.brandName+" |Frame Color: "+spec11.frameColor+"|Price: "+spec11.price+" |Type of Lens: "+spec11.lens+" |Frame Width: "+	spec11.frameWidth);
	Specs spec12=new Specs();
	spec12.frameColor="Green";
	spec12.brandName="lensKart";
	spec12.price=1768 ;
	spec12.lens="-0.50";
	spec12.frameWidth=132;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec12.brandName+" |Frame Color: "+spec12.frameColor+" |Price: "+spec12.price+" |Type of Lens: "+spec12.lens+"|Frame Width: "+	spec12.frameWidth);
	Specs spec13=new Specs();
	spec13.frameColor="Gold";
	spec13.brandName="lensKart";
	spec13.price=1768 ;
	spec13.lens="-0.50";
	spec13.frameWidth=133;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec13.brandName+" |Frame Color: "+spec13.frameColor+" |Price: "+spec13.price+" |Type of Lens: "+spec13.lens+"|Frame Width: "+	spec13.frameWidth);
	Specs spec14=new Specs();
	spec14.frameColor="Black";
	spec14.brandName="lensKart";
	spec14.price=1768 ;
	spec14.lens="-0.50";
	spec14.frameWidth=133;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec14.brandName+" |Frame Color: "+spec14.frameColor+" |Price: "+spec14.price+"|Type of Lens: "+spec14.lens+"|Frame Width: "+	spec14.frameWidth);
	Specs spec15=new Specs();
	spec15.frameColor="Camel";
	spec15.brandName="lensKart";
	spec15.price=1796 ;
	spec15.lens="-0.30";
	spec15.frameWidth=133;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec15.brandName+" |Frame Color: "+spec15.frameColor+" |Price: "+spec15.price+" |Type of Lens: "+spec15.lens+" |Frame Width: "+	spec15.frameWidth);
	Specs spec16=new Specs();
	spec16.frameColor="Peach";
	spec16.brandName="lensKart";
	spec16.price=1768 ;
	spec16.lens="-0.50";
	spec16.frameWidth=133;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec16.brandName+" |Frame Color: "+spec16.frameColor+" |Price: "+spec16.price+" |Type of Lens: "+spec16.lens+" |Frame Width: "+	spec16.frameWidth);
	Specs spec17=new Specs();
	spec17.frameColor="Coral";
	spec17.brandName="lensKart";
	spec17.price=968 ;
	spec17.lens="-0.40";
	spec17.frameWidth=123; 
	spec1.clearVision();
	System.out.println("Brand Name: "+spec17.brandName+" |Frame Color: "+spec17.frameColor+" |Price: "+spec17.price+" |Type of Lens: "+spec17.lens+" |Frame Width: "+	spec17.frameWidth);
	Specs spec18=new Specs();
	spec18.frameColor="Cream";
	spec18.brandName="lensKart";
	spec18.price=1768 ;
	spec18.lens="-0.50";
	spec18.frameWidth=133;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec18.brandName+" |Frame Color: "+spec18.frameColor+" |Price: "+spec18.price+" |Type of Lens: "+spec18.lens+" |Frame Width: "+	spec18.frameWidth);
	Specs spec19=new Specs();
	spec19.frameColor="Rust";
	spec19.brandName="lensKart";
	spec19.price=768 ;
	spec19.lens="-0.30";
	spec19.frameWidth=132;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec19.brandName+" |Frame Color: "+spec19.frameColor+" |Price: "+spec19.price+" |Type of Lens: "+spec19.lens+" |Frame Width: "+	spec19.frameWidth);
	Specs spec20=new Specs();
	spec20.frameColor="Gray";
	spec20.brandName="lensKart";
	spec20.price=3768 ;
	spec20.lens="-0.30";
	spec20.frameWidth=132;
	spec1.clearVision();
	System.out.println("Brand Name: "+spec20.brandName+" |Frame Color: "+spec20.frameColor+" |Price: "+spec20.price+" |Type of Lens: "+spec20.lens+" |Frame Width: "+	spec20.frameWidth);
}


}