class WatchTester{
	public static void main(String time[]){
		Watch watch=new Watch();
		watch.type="Anaolog";
		watch.brandName="Fastrack";
		watch.price=3567;
		watch.color="Silver Chain";
		watch.Time();
		System.out.println("Watch type:"+	watch.type+"  Brand:"+watch.brandName+"  Price:"+watch.price+"  Color:"+watch.color);
		Watch watch1=new Watch();
		watch1.type="Anaolog";
		watch1.brandName="STUDIO ETHENO";
		watch1.price=1567;
		watch1.color="Black Belt";
		watch1.Time();
		System.out.println("Watch type:"+	watch1.type+"  Brand:"+watch1.brandName+"  Price:"+watch1.price+"  Color:"+watch1.color);
		Watch watch2=new Watch();
		watch2.type="Anaolog";
		watch2.brandName="Sonata";
		watch2.price=3567;
		watch2.color="Silver Chain";
		watch.Time();
		System.out.println("Watch type:"+	watch2.type+"  Brand:"+watch2.brandName+"  Price:"+watch2.price+"  Color:"+watch2.color);
		Watch watch3=new Watch();
		watch3.type="Anaolog";
		watch3.brandName="Acnos Brand";
		watch3.price=567;
		watch3.color="Rose Red Belt";
		watch.Time();
		System.out.println("Watch type:"+	watch3.type+"  Brand:"+watch3.brandName+"  Price:"+watch3.price+"  Color:"+watch3.color);
		Watch watch4=new Watch();
		watch4.type="Anaolog";
		watch4.brandName="Urwerk Ur-Satellite";
		watch4.price=113567;
		watch4.color="Black Belt";
		watch.Time();
		System.out.println("Watch type:"+	watch4.type+"  Brand:"+watch4.brandName+"  Price:"+watch4.price+"  Color:"+watch4.color);
		Watch watch6=new Watch();
		watch6.type="Anaolog";
		watch6.brandName="Peter England";
		watch6.price=1567;
		watch6.color="Black Chanin";
		watch.Time();
		System.out.println("Watch type:"+	watch6.type+"  Brand:"+watch6.brandName+"  Price:"+watch6.price+"  Color:"+watch6.color);
		Watch watch7=new Watch();
		watch7.type="Anaolog";
		watch7.brandName="Fastrack";
		watch7.price=3567;
		watch7.color="Silver";
		watch.Time();
		System.out.println("Watch type:"+	watch7.type+"  Brand:"+watch7.brandName+"  Price:"+watch7.price+"  Color:"+watch7.color);
		Watch watch8=new Watch();
		watch8.type="Anaolog";
		watch8.brandName="Roylex";
		watch8.price=20567;
		watch8.color="Gold Chain";
		watch.Time();
		System.out.println("Watch type:"+	watch8.type+"  Brand:"+watch8.brandName+"  Price:"+watch8.price+"  Color:"+watch8.color);
		Watch watch9=new Watch();
		watch9.type="Anaolog";
		watch9.brandName="Mast&Harbour";
		watch9.price=1567;
		watch9.color="Black Belt";
		watch.Time();
		System.out.println("Watch type:"+	watch9.type+"  Brand:"+watch9.brandName+"  Price:"+watch9.price+"  Color:"+watch9.color);
		Watch watch10=new Watch();
		watch10.type="Anaolog";
		watch10.brandName="hmct";
		watch10.price=4536;
		watch10.color="SilverGold mix chain";
		watch.Time();
		System.out.println("Watch type:"+	watch10.type+"  Brand:"+watch10.brandName+"  Price:"+watch10.price+"  Color:"+watch10.color);
		Watch watch11=new Watch();
		watch11.type="Anaolog";
		watch11.brandName="WROGN";
		watch11.price=2967;
		watch11.color="Blue Belt";
		watch.Time();
		System.out.println("Watch type:"+	watch11.type+"  Brand:"+watch11.brandName+"  Price:"+watch11.price+"  Color:"+watch11.color);
		Watch watch12=new Watch();
		watch12.type="Digital";
		watch12.brandName="boAt Xtend";
		watch12.price=1499;
		watch12.color="Black";
		watch.Time();
		System.out.println("Watch type:"+	watch12.type+"  Brand:"+watch12.brandName+"  Price:"+watch12.price+"  Color:"+watch12.color);
		Watch watch13=new Watch();
		watch13.type="Digital";
		watch13.brandName="Daniel Klein Men";
		watch13.price=2543;
		watch13.color="White";
		watch.Time();
		System.out.println("Watch type:"+	watch13.type+"  Brand:"+watch13.brandName+"  Price:"+watch13.price+"  Color:"+watch13.color);
		Watch watch14=new Watch();
		watch14.type="Digital";
		watch14.brandName="Fastrack";
		watch14.price=3567;
		watch14.color="Silver";
		watch.Time();
		System.out.println("Watch type:"+	watch14.type+"  Brand:"+watch14.brandName+"  Price:"+watch14.price+"  Color:"+watch14.color);
		Watch watch15=new Watch();
		watch15.type="Digital";
		watch15.brandName="Sonata";
		watch15.price=2567;
		watch15.color="Black";
		watch.Time();
		System.out.println("Watch type:"+	watch.type+"  Brand:"+watch.brandName+"  Price:"+watch.price+"  Color:"+watch.color);
		Watch watch16=new Watch();
		watch16.type="Digital";
		watch16.brandName="Casio";
		watch16.price=8567;
		watch16.color="Black";
		watch.Time();
		System.out.println("Watch type:"+	watch16.type+"  Brand:"+watch16.brandName+"  Price:"+watch16.price+"  Color:"+watch16.color);
		Watch watch17=new Watch();
		watch17.type="Digital";
		watch17.brandName="Casio Vintage";
		watch17.price=4597;
		watch17.color="White";
		watch.Time();
		System.out.println("Watch type:"+	watch17.type+"  Brand:"+watch17.brandName+"  Price:"+watch17.price+"  Color:"+watch17.color);
		Watch watch18=new Watch();
		watch18.type="Digital";
		watch18.brandName="Fastrack";
		watch18.price=5467;
		watch18.color="White";
		watch.Time();
		System.out.println("Watch type:"+	watch18.type+"  Brand:"+watch18.brandName+"  Price:"+watch18.price+"  Color:"+watch18.color);
		Watch watch19=new Watch();
		watch19.type="Digital";
		watch19.brandName="Realme";
		watch19.price=2567;
		watch19.color="Black";
		watch.Time();
		System.out.println("Watch type:"+	watch19.type+"  Brand:"+watch19.brandName+"  Price:"+watch19.price+"  Color:"+watch19.color);
		Watch watch20=new Watch();
		watch20.type="Digital";
		watch20.brandName="NaviForce";
		watch20.price=3186;
		watch20.color="Silver";
		watch20.Time();
		System.out.println("Watch type:"+	watch20.type+"  Brand:"+watch20.brandName+"  Price:"+watch20.price+"  Color:"+watch20.color);
	}
}